#!/bin/bash

ns=notify-send
dmenu='dmenu -m 0 -fn VictorMono:size=20 -nf green -nb black -nf green -sb black'
dun='dunstify -u low'

LIST=$(kubectl get crd -A | awk '{print $1, $2}' | fzf --layout reverse)

kubectl describe crd -n ${LIST}
   if [ "$?" -eq 0 ]; then
       ${DUN} "SELCTED!"
   else
       dunstify -u critical "No Pod Selected"
       exit 1
   fi
