#!/bin/bash
set -x

function tm() {
    ARG=$@
    echo "$@" | terminal-notifier 
}
function flist() {
    POD=$@
    fzf --reverse --border --border-label="$POD"
}

INGRESS=$(kubectl get ingress -A | awk '{print $1, $2, $4}' | $(flist "Pod Ingresses")| awk '{print $1, $2}')
#CONTAINER=$(kubectl get ing -n ${INGRESS} -o jsonpath='{range .spec.containers[*]}{.name}{"\n"}{end}' | fzf --layout reverse)
#CONTAINER=$(kubectl get po -n ${INGRESS} -o jsonpath='{range .spec.containers[*]}{.name}{"\n"}{end}' | fzf --layout reverse)

kubectl logs -n ${INGRESS} #-c ${CONTAINER}
   if [ "$?" -eq 0 ]; then
       $(tm "Ingress Selected!")
#       ${tm} "SELCTED!"
   else
       $(tm "Ingress Not Found")
       exit 1
   fi
